# Generated by Django 5.1.3 on 2024-11-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alumno_rename_nickame_programmer_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
