# Generated by Django 5.1.3 on 2024-11-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_programmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
    ]
