# Generated by Django 5.1.3 on 2024-11-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rol_alumnorol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo_rol',
            field=models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin'), ('SUPERUSER', 'superuser')], default='user', max_length=50),
        ),
    ]
