# Generated by Django 5.1.3 on 2024-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rol_tipo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
