# Generated by Django 5.1.3 on 2024-11-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alumno_asignaturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('calificacion', models.IntegerField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.alumno')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.asignatura')),
            ],
            options={
                'unique_together': {('id_alumno', 'id_asignatura', 'trimestre')},
            },
        ),
    ]
